# Generated by Django 5.2.5 on 2026-01-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_radiator_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiator',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='radiator',
            name='part_type',
            field=models.CharField(choices=[('Radiator', 'Radiator'), ('Oil Cooler', 'Oil Cooler'), ('Intercooler', 'Intercooler'), ('Fuel Tank', 'Fuel Tank'), ('Other', 'Other')], default='Radiator', max_length=50),
        ),
    ]
