# Generated by Django 5.2.5 on 2026-01-03 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_radiator_invoice_number_and_more'),
        ('jobs', '0002_job_date_completed_job_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('radiator', 'Radiator')], max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('work_type', models.CharField(blank=True, choices=[('repair', 'Repair'), ('service', 'Service'), ('radiator_replacement', 'Radiator Replacement'), ('other', 'Other')], max_length=50, null=True)),
                ('part_type', models.CharField(blank=True, choices=[('Radiator', 'Radiator'), ('Oil Cooler', 'Oil Cooler'), ('Intercooler', 'Intercooler'), ('Fuel Tank', 'Fuel Tank'), ('Other', 'Other')], max_length=50, null=True)),
                ('description', models.CharField(help_text='Vehicle details or Radiator/Part description', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='jobs.job')),
                ('linked_radiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='inventory.radiator')),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
    ]
