# Generated by Django 5.2.5 on 2026-01-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_make',
            field=models.CharField(blank=True, help_text='Vehicle make (e.g., Toyota, Ford)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., Corolla, Focus)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_registration',
            field=models.CharField(blank=True, help_text='Vehicle registration number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, help_text='Radiator/Part description', max_length=500, null=True),
        ),
    ]
